---
# tasks file for hivemind
- name: Check installed Go and get version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Hivemind | Set GOPATH for all users
  when: go_version is defined
  copy: src=go-path.sh
        dest=/etc/profile.d

- name: Hivemind | Run shell
  shell: sh /etc/profile.d/go-path.sh
  sudo: yes

- name: Hivemind | Installing through Golang
  shell: go get -u {{ hivemind_repo }}
  when: go_version is defined
