---
# tasks file for hivemind
- name: Check installed Go and get version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Install | Ensure that GOPATH exists
  file: path={{ golang_gopath }} state=directory
  sudo: yes

- name: Install | Ensure that GOPATH is owned by current user
  shell: chown -R {{ deploy_user }} {{ golang_gopath }}
  sudo: yes

- name: Configure | Set GOPATH for all users and add to PATH
  copy: src=go-path.sh
        dest=/etc/profile.d
  sudo: yes

- name: Hivemind | Installing through Golang
  command: go get {{ hivemind_repo }} creates={{golang_gopath}}/bin/hovemind
  environment: golang_env
