---
# tasks file for hivemind
- name: Check installed Go and get version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Hivemind | create directory
  file: path=go state=directory

- name: Hivemind | export GOPATH
  shell: export GOPATH=$HOME/go
  sudo: no

- name: Hivemind | export PATH
  shell: export PATH=$PATH:$GOPATH/bin

- name: Hivemind | Installing through Golang
  shell: go get -u {{ hivemind_repo }}
  when: go_version is defined
